create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  customer_phone text not null default '',
  item_name text not null,
  category text not null,
  photo_key text,
  selling_price bigint not null check (selling_price >= 0),
  wholesale_price bigint check (wholesale_price >= 0),
  extra_costs bigint not null default 0 check (extra_costs >= 0),
  amount_paid bigint not null default 0 check (amount_paid >= 0),
  payment_method text not null default 'Cash',
  status text not null default 'New order',
  due_date text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  amount bigint not null check (amount > 0),
  expense_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists expenses_user_date_idx on public.expenses(user_id, expense_date desc);

alter table public.orders enable row level security;
alter table public.expenses enable row level security;
revoke all on table public.orders, public.expenses from anon;
grant select, insert, update, delete on table public.orders, public.expenses to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Users manage their own orders" on public.orders;
create policy "Users manage their own orders"
on public.orders for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their own expenses" on public.expenses;
create policy "Users manage their own expenses"
on public.expenses for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('order-photos', 'order-photos', false, 8388608, array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users read their own order photos" on storage.objects;
create policy "Users read their own order photos"
on storage.objects for select to authenticated
using (bucket_id = 'order-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Users upload their own order photos" on storage.objects;
create policy "Users upload their own order photos"
on storage.objects for insert to authenticated
with check (bucket_id = 'order-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Users update their own order photos" on storage.objects;
create policy "Users update their own order photos"
on storage.objects for update to authenticated
using (bucket_id = 'order-photos' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'order-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Users delete their own order photos" on storage.objects;
create policy "Users delete their own order photos"
on storage.objects for delete to authenticated
using (bucket_id = 'order-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
